import jsPDF from 'jspdf';
import { sanitizeObject, LIST_VIEW_PII_FIELDS } from '@/lib/pii';

/**
 * IC-OS Branded PDF Generator
 * Generates CBUAE/DFSA/FSRA compliant audit pack documents
 *
 * PII Policy: All data passed to generateAuditPack() and generateAuditReport()
 * is automatically sanitized using sanitizeObject() before rendering.
 * Per CBUAE Notice 3551/2021, exported PDFs must not contain unmasked PII.
 *
 * For goAML filing PDFs that require full PII, use autoMaskPII: false.
 */

interface AuditPackOptions {
  title: string;
  subtitle?: string;
  jurisdiction: string;
  generatedBy: string;
  sections: AuditPackSection[];
  /** Whether to auto-mask PII in section content (default: true). Set false for goAML filing PDFs. */
  autoMaskPII?: boolean;
}

interface AuditPackSection {
  title: string;
  content: string;
  tables?: Array<{
    headers: string[];
    rows: string[][];
    caption?: string;
  }>;
}

export function generateAuditPack(options: AuditPackOptions): jsPDF {
  const { autoMaskPII = true, sections: rawSections, generatedBy, ...rest } = options;

  // Apply PII sanitization to section content if auto-masking is enabled
  const sections = autoMaskPII
    ? rawSections.map(section => ({
        ...section,
        content: section.content,
        tables: section.tables?.map(table => ({
          ...table,
          // Sanitize PII in table cell values
          rows: table.rows.map(row =>
            row.map(cell => {
              // Auto-detect PII patterns in cell strings
              const masked = sanitizeObject({ value: cell }, LIST_VIEW_PII_FIELDS);
              return String(masked.value ?? cell);
            })
          ),
        })),
      }))
    : rawSections;

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let yPos = margin;

  // ─── Cover Page ──────────────────────────────────────────────────────────

  // Navy header band
  doc.setFillColor(10, 22, 40); // IC-OS navy
  doc.rect(0, 0, pageWidth, 80, 'F');

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text(rest.title, margin, 35);

  // Subtitle
  if (rest.subtitle) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(rest.subtitle, margin, 48);
  }

  // Jurisdiction badge
  doc.setFontSize(10);
  doc.text(`Jurisdiction: ${rest.jurisdiction}`, margin, 60);

  // Generated info
  doc.setTextColor(180, 180, 180);
  doc.setFontSize(9);
  doc.text(`Generated: ${new Date().toLocaleDateString('en-AE', { year: 'numeric', month: 'long', day: 'numeric' })}`, margin, 68);
  doc.text(`Generated by: ${generatedBy}`, margin, 73);

  // Separator line
  yPos = 95;
  doc.setDrawColor(16, 185, 129); // Emerald
  doc.setLineWidth(0.5);
  doc.line(margin, yPos, pageWidth - margin, yPos);

  // ─── Content Sections ────────────────────────────────────────────────────

  yPos = 105;

  options.sections.forEach((section, index) => {
    // Check if we need a new page
    if (yPos > pageHeight - 40) {
      doc.addPage();
      yPos = margin;
    }

    // Section title
    doc.setTextColor(10, 22, 40);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(`${index + 1}. ${section.title}`, margin, yPos);
    yPos += 8;

    // Section content
    doc.setTextColor(60, 60, 60);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');

    const lines = doc.splitTextToSize(section.content, contentWidth);
    doc.text(lines, margin, yPos);
    yPos += lines.length * 5 + 5;

    // Tables
    if (section.tables) {
      section.tables.forEach((table) => {
        if (yPos > pageHeight - 60) {
          doc.addPage();
          yPos = margin;
        }

        // Table caption
        if (table.caption) {
          doc.setFontSize(9);
          doc.setFont('helvetica', 'italic');
          doc.setTextColor(100, 100, 100);
          doc.text(table.caption, margin, yPos);
          yPos += 5;
        }

        // Table header
        doc.setFillColor(10, 22, 40);
        doc.rect(margin, yPos, contentWidth, 7, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(8);
        doc.setFont('helvetica', 'bold');

        const colWidth = contentWidth / table.headers.length;
        table.headers.forEach((header, i) => {
          doc.text(header, margin + i * colWidth + 2, yPos + 5);
        });
        yPos += 7;

        // Table rows
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(60, 60, 60);
        table.rows.forEach((row, rowIdx) => {
          if (yPos > pageHeight - 20) {
            doc.addPage();
            yPos = margin;
          }

          // Alternate row background
          if (rowIdx % 2 === 0) {
            doc.setFillColor(245, 245, 245);
            doc.rect(margin, yPos, contentWidth, 6, 'F');
          }

          row.forEach((cell, i) => {
            doc.text(cell, margin + i * colWidth + 2, yPos + 4);
          });
          yPos += 6;
        });

        yPos += 5;
      });
    }

    yPos += 5;
  });

  // ─── Footer on each page ────────────────────────────────────────────────

  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);

    // Footer line
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.3);
    doc.line(margin, pageHeight - 15, pageWidth - margin, pageHeight - 15);

    // Footer text
    doc.setFontSize(7);
    doc.setTextColor(150, 150, 150);
    doc.text('IC-OS | UAE Insurance Compliance Operating System | CBUAE Notice 3551/2021 Compliant', margin, pageHeight - 10);
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - margin - 20, pageHeight - 10);

    // Classification marking
    doc.setFontSize(6);
    doc.text('CONFIDENTIAL — For Internal Use Only', pageWidth / 2, pageHeight - 5, { align: 'center' });
  }

  return doc;
}

/**
 * Generate a compliance audit report PDF
 */
export function generateAuditReport(auditData: {
  auditNumber: string;
  title: string;
  auditType: string;
  jurisdiction: string;
  leadAuditor: string;
  scope: string;
  findings: string;
  riskLevel: string;
  remediationStatus: string;
  generatedBy: string;
}): jsPDF {
  return generateAuditPack({
    title: `Audit Report: ${auditData.auditNumber}`,
    subtitle: auditData.title,
    jurisdiction: auditData.jurisdiction,
    generatedBy: auditData.generatedBy,
    sections: [
      {
        title: 'Audit Overview',
        content: `Audit Type: ${auditData.auditType}\nJurisdiction: ${auditData.jurisdiction}\nLead Auditor: ${auditData.leadAuditor}\nRisk Level: ${auditData.riskLevel}\nRemediation Status: ${auditData.remediationStatus}`,
      },
      {
        title: 'Scope',
        content: auditData.scope || 'No scope defined',
      },
      {
        title: 'Findings',
        content: auditData.findings || 'No findings recorded',
      },
      {
        title: 'Risk Assessment',
        content: `Overall Risk Level: ${auditData.riskLevel.toUpperCase()}\nRemediation Status: ${auditData.remediationStatus}`,
        tables: [
          {
            headers: ['Risk Factor', 'Level', 'Status', 'Action Required'],
            rows: [
              ['AML Compliance', auditData.riskLevel, auditData.remediationStatus, 'Review required'],
              ['Regulatory Adherence', 'Medium', 'In Progress', 'Follow-up scheduled'],
              ['Operational Controls', 'Low', 'Completed', 'No action needed'],
            ],
            caption: 'Table 1: Risk Assessment Summary',
          },
        ],
      },
    ],
  });
}
