/**
 * goAML XML Generation Utility — IC-OS Compliance Platform
 * Generates goAML v4.2 compliant XML for all 5 UAE FIU report types.
 * References: FDL 10/2025, CBUAE goAML Specification v4.2
 *
 * Report Types: STR, SAR, CTR, IFT, PNMR
 * UAE-Specific: amountAED, jurisdiction, emiratesId
 * Thresholds:  CTR auto-trigger at AED 55,000; CBWT at AED 3,500
 */

// ─── Types ──────────────────────────────────────────────────────────────────

export type GoAMLReportType = 'STR' | 'SAR' | 'CTR' | 'IFT' | 'PNMR';

export interface GoAMLFilingData {
  reportType: GoAMLReportType;
  referenceNumber?: string;
  subjectName: string;
  amountAED: number;
  currency?: string;
  narrative?: string;
  transactionDate?: string;
  jurisdiction?: string;
  emiratesId?: string;
  identifiers?: {
    passportNo?: string;
    nationality?: string;
    dateOfBirth?: string;
    phone?: string;
    email?: string;
    address?: string;
    accountNumber?: string;
    beneficiaryName?: string;
    beneficiaryAccount?: string;
    originatingCountry?: string;
    destinationCountry?: string;
    transactionType?: string;
  };
  filingEntity?: {
    name?: string;
    licenseNumber?: string;
    trn?: string;
    address?: string;
    contactPerson?: string;
    contactPhone?: string;
  };
}

export interface XMLValidationResult {
  isValid: boolean;
  errors: XMLValidationError[];
  warnings: string[];
}

export interface XMLValidationError {
  path: string;
  message: string;
  severity: 'error' | 'warning';
}

// ─── Constants ──────────────────────────────────────────────────────────────

const GOAML_VERSION = '4.2';
const GOAML_NAMESPACE = 'http://www.fatf-gafi.org/goaml/v4.2';
const CTR_THRESHOLD_AED = 55_000;
const CBWT_THRESHOLD_AED = 3_500;
const UAE_CURRENCY = 'AED';

const REPORT_TYPE_CODES: Record<GoAMLReportType, string> = {
  STR: 'STR',
  SAR: 'SAR',
  CTR: 'CTR',
  IFT: 'IFT',
  PNMR: 'PNMR',
};

// ─── XML Escape Helper ─────────────────────────────────────────────────────

function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

// ─── XML Header Generator ──────────────────────────────────────────────────

function generateXmlHeader(reportType: GoAMLReportType): string {
  const timestamp = new Date().toISOString();
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    `<!-- goAML v${GOAML_VERSION} | Report Type: ${reportType} | Generated by IC-OS Compliance Platform -->`,
    `<!-- Regulatory Reference: FDL 10/2025 (CBUAE Federal Decree-Law No. 10 of 2025 on Anti-Money Laundering) -->`,
    `<!-- Generated: ${timestamp} -->`,
  ].join('\n');
}

// ─── Reporting Entity Section ───────────────────────────────────────────────

function generateReportingEntitySection(filing: GoAMLFilingData): string {
  const entity = filing.filingEntity;
  return [
    '  <ReportingEntity>',
    `    <Name>${escapeXml(entity?.name || 'IC-OS Reporting Entity')}</Name>`,
    `    <LicenseNumber>${escapeXml(entity?.licenseNumber || 'CN-XXXX')}</LicenseNumber>`,
    entity?.trn ? `    <TRN>${escapeXml(entity.trn)}</TRN>` : '',
    entity?.address ? `    <Address>${escapeXml(entity.address)}</Address>` : '',
    entity?.contactPerson ? `    <ContactPerson>${escapeXml(entity.contactPerson)}</ContactPerson>` : '',
    entity?.contactPhone ? `    <ContactPhone>${escapeXml(entity.contactPhone)}</ContactPhone>` : '',
    `    <Jurisdiction>${escapeXml(filing.jurisdiction || 'AE')}</Jurisdiction>`,
    '  </ReportingEntity>',
  ].filter(Boolean).join('\n');
}

// ─── Subject / Person Section ───────────────────────────────────────────────

function generateSubjectSection(filing: GoAMLFilingData): string {
  const ids = filing.identifiers;
  return [
    '  <Subject>',
    '    <Person>',
    `      <FullName>${escapeXml(filing.subjectName)}</FullName>`,
    filing.emiratesId ? `      <EmiratesID>${escapeXml(filing.emiratesId)}</EmiratesID>` : '',
    ids?.passportNo ? `      <PassportNumber>${escapeXml(ids.passportNo)}</PassportNumber>` : '',
    ids?.nationality ? `      <Nationality>${escapeXml(ids.nationality)}</Nationality>` : '',
    ids?.dateOfBirth ? `      <DateOfBirth>${escapeXml(ids.dateOfBirth)}</DateOfBirth>` : '',
    ids?.phone ? `      <Phone>${escapeXml(ids.phone)}</Phone>` : '',
    ids?.email ? `      <Email>${escapeXml(ids.email)}</Email>` : '',
    ids?.address ? `      <Address>${escapeXml(ids.address)}</Address>` : '',
    '    </Person>',
    ids?.accountNumber ? `    <AccountNumber>${escapeXml(ids.accountNumber)}</AccountNumber>` : '',
    '  </Subject>',
  ].filter(Boolean).join('\n');
}

// ─── Transaction Section ────────────────────────────────────────────────────

function generateTransactionSection(filing: GoAMLFilingData): string {
  const ids = filing.identifiers;
  const txDate = filing.transactionDate || new Date().toISOString().split('T')[0];

  return [
    '  <Transaction>',
    `    <Date>${escapeXml(txDate)}</Date>`,
    `    <Amount>${filing.amountAED.toFixed(2)}</Amount>`,
    `    <Currency>${filing.currency || UAE_CURRENCY}</Currency>`,
    `    <AmountAED>${filing.amountAED.toFixed(2)}</AmountAED>`,
    ids?.transactionType ? `    <Type>${escapeXml(ids.transactionType)}</Type>` : '',
    ids?.originatingCountry ? `    <OriginatingCountry>${escapeXml(ids.originatingCountry)}</OriginatingCountry>` : '',
    ids?.destinationCountry ? `    <DestinationCountry>${escapeXml(ids.destinationCountry)}</DestinationCountry>` : '',
    '    <Beneficiary>',
    ids?.beneficiaryName ? `      <Name>${escapeXml(ids.beneficiaryName)}</Name>` : '',
    ids?.beneficiaryAccount ? `      <AccountNumber>${escapeXml(ids.beneficiaryAccount)}</AccountNumber>` : '',
    '    </Beneficiary>',
    '  </Transaction>',
  ].filter(Boolean).join('\n');
}

// ─── Narrative Section ──────────────────────────────────────────────────────

function generateNarrativeSection(filing: GoAMLFilingData): string {
  if (!filing.narrative) return '';
  return [
    '  <Narrative>',
    `    <Text>${escapeXml(filing.narrative)}</Text>`,
    '  </Narrative>',
  ].join('\n');
}

// ─── CTR Auto-Detection ─────────────────────────────────────────────────────

/**
 * Auto-detect if a CTR should be generated based on amount threshold.
 * Per FDL 10/2025, CTR is mandatory for cash transactions >= AED 55,000.
 */
export function shouldAutoGenerateCTR(amountAED: number): boolean {
  return amountAED >= CTR_THRESHOLD_AED;
}

/**
 * Check if the CBWT (Cross-Border Wire Transfer) threshold applies.
 * Per FDL 10/2025, enhanced due diligence applies at >= AED 3,500.
 */
export function isCBWTThreshold(amountAED: number): boolean {
  return amountAED >= CBWT_THRESHOLD_AED;
}

/**
 * Get the effective report type, auto-detecting CTR when applicable.
 */
export function detectReportType(filing: GoAMLFilingData): GoAMLReportType {
  if (filing.reportType !== 'CTR' && shouldAutoGenerateCTR(filing.amountAED)) {
    return 'CTR';
  }
  return filing.reportType;
}

// ─── Report-Specific XML Generators ─────────────────────────────────────────

/**
 * Generate STR (Suspicious Transaction Report) XML
 * Used for transactions suspected to be related to ML/TF.
 */
export function generateSTRXml(filing: GoAMLFilingData): string {
  const ref = filing.referenceNumber || `STR-${Date.now()}`;
  const lines: string[] = [
    generateXmlHeader('STR'),
    `<goAML xmlns="${GOAML_NAMESPACE}" version="${GOAML_VERSION}">`,
    `  <ReportHeader>`,
    `    <ReportCode>${REPORT_TYPE_CODES.STR}</ReportCode>`,
    `    <ReferenceNumber>${escapeXml(ref)}</ReferenceNumber>`,
    `    <FilingDate>${new Date().toISOString()}</FilingDate>`,
    `    <RegulatoryReference>FDL 10/2025</RegulatoryReference>`,
    `    <Jurisdiction>${escapeXml(filing.jurisdiction || 'AE')}</Jurisdiction>`,
    `    <SubmissionType>INITIAL</SubmissionType>`,
    `  </ReportHeader>`,
    generateReportingEntitySection(filing),
    generateSubjectSection(filing),
    generateTransactionSection(filing),
    generateNarrativeSection(filing),
    '  <SuspiciousActivity>',
    '    <Reason>Transaction flagged as suspicious per AML/CFT monitoring rules</Reason>',
    '    <DateDetected>' + new Date().toISOString().split('T')[0] + '</DateDetected>',
    '    <ReportingObligation>FDL 10/2025 Article 14</ReportingObligation>',
    '  </SuspiciousActivity>',
    '</goAML>',
  ];
  return lines.join('\n');
}

/**
 * Generate SAR (Suspicious Activity Report) XML
 * Broader than STR — covers non-transactional suspicious activity.
 */
export function generateSARXml(filing: GoAMLFilingData): string {
  const ref = filing.referenceNumber || `SAR-${Date.now()}`;
  const lines: string[] = [
    generateXmlHeader('SAR'),
    `<goAML xmlns="${GOAML_NAMESPACE}" version="${GOAML_VERSION}">`,
    `  <ReportHeader>`,
    `    <ReportCode>${REPORT_TYPE_CODES.SAR}</ReportCode>`,
    `    <ReferenceNumber>${escapeXml(ref)}</ReferenceNumber>`,
    `    <FilingDate>${new Date().toISOString()}</FilingDate>`,
    `    <RegulatoryReference>FDL 10/2025</RegulatoryReference>`,
    `    <Jurisdiction>${escapeXml(filing.jurisdiction || 'AE')}</Jurisdiction>`,
    `    <SubmissionType>INITIAL</SubmissionType>`,
    `  </ReportHeader>`,
    generateReportingEntitySection(filing),
    generateSubjectSection(filing),
    generateTransactionSection(filing),
    generateNarrativeSection(filing),
    '  <SuspiciousActivity>',
    '    <Reason>Suspicious activity identified during compliance review</Reason>',
    '    <DateDetected>' + new Date().toISOString().split('T')[0] + '</DateDetected>',
    '    <ReportingObligation>FDL 10/2025 Article 14; CBUAE Guidance Note 3/2025</ReportingObligation>',
    '  </SuspiciousActivity>',
    '</goAML>',
  ];
  return lines.join('\n');
}

/**
 * Generate CTR (Currency Transaction Report) XML
 * Mandatory for cash transactions >= AED 55,000 (FDL 10/2025).
 */
export function generateCTRXml(filing: GoAMLFilingData): string {
  const ref = filing.referenceNumber || `CTR-${Date.now()}`;
  const isCBWT = isCBWTThreshold(filing.amountAED);
  const lines: string[] = [
    generateXmlHeader('CTR'),
    `<goAML xmlns="${GOAML_NAMESPACE}" version="${GOAML_VERSION}">`,
    `  <ReportHeader>`,
    `    <ReportCode>${REPORT_TYPE_CODES.CTR}</ReportCode>`,
    `    <ReferenceNumber>${escapeXml(ref)}</ReferenceNumber>`,
    `    <FilingDate>${new Date().toISOString()}</FilingDate>`,
    `    <RegulatoryReference>FDL 10/2025</RegulatoryReference>`,
    `    <Jurisdiction>${escapeXml(filing.jurisdiction || 'AE')}</Jurisdiction>`,
    `    <SubmissionType>INITIAL</SubmissionType>`,
    `  </ReportHeader>`,
    generateReportingEntitySection(filing),
    generateSubjectSection(filing),
    generateTransactionSection(filing),
    generateNarrativeSection(filing),
    '  <CurrencyTransaction>',
    `    <ThresholdAmount>${CTR_THRESHOLD_AED.toFixed(2)}</ThresholdAmount>`,
    `    <ThresholdCurrency>${UAE_CURRENCY}</ThresholdCurrency>`,
    `    <ExceedsThreshold>${(filing.amountAED >= CTR_THRESHOLD_AED).toString()}</ExceedsThreshold>`,
    isCBWT ? `    <CBWT>true</CBWT>` : '',
    isCBWT ? `    <CBWTThreshold>${CBWT_THRESHOLD_AED.toFixed(2)}</CBWTThreshold>` : '',
    '    <ReportingObligation>FDL 10/2025 Article 15; CBUAE CTR Filing Requirements</ReportingObligation>',
    '  </CurrencyTransaction>',
    '</goAML>',
  ];
  return lines.filter(Boolean).join('\n');
}

/**
 * Generate IFT (International Funds Transfer) XML
 * For cross-border wire transfers requiring Travel Rule compliance.
 */
export function generateIFTXml(filing: GoAMLFilingData): string {
  const ref = filing.referenceNumber || `IFT-${Date.now()}`;
  const ids = filing.identifiers;
  const lines: string[] = [
    generateXmlHeader('IFT'),
    `<goAML xmlns="${GOAML_NAMESPACE}" version="${GOAML_VERSION}">`,
    `  <ReportHeader>`,
    `    <ReportCode>${REPORT_TYPE_CODES.IFT}</ReportCode>`,
    `    <ReferenceNumber>${escapeXml(ref)}</ReferenceNumber>`,
    `    <FilingDate>${new Date().toISOString()}</FilingDate>`,
    `    <RegulatoryReference>FDL 10/2025</RegulatoryReference>`,
    `    <Jurisdiction>${escapeXml(filing.jurisdiction || 'AE')}</Jurisdiction>`,
    `    <SubmissionType>INITIAL</SubmissionType>`,
    `  </ReportHeader>`,
    generateReportingEntitySection(filing),
    generateSubjectSection(filing),
    generateTransactionSection(filing),
    generateNarrativeSection(filing),
    '  <InternationalTransfer>',
    ids?.originatingCountry ? `    <OriginatingCountry>${escapeXml(ids.originatingCountry)}</OriginatingCountry>` : '    <OriginatingCountry>AE</OriginatingCountry>',
    ids?.destinationCountry ? `    <DestinationCountry>${escapeXml(ids.destinationCountry)}</DestinationCountry>` : '',
    '    <TravelRuleCompliant>true</TravelRuleCompliant>',
    isCBWTThreshold(filing.amountAED) ? `    <CBWT>true</CBWT>` : '',
    '    <ReportingObligation>FDL 10/2025 Article 16; FATF Travel Rule</ReportingObligation>',
    '  </InternationalTransfer>',
    '</goAML>',
  ];
  return lines.filter(Boolean).join('\n');
}

/**
 * Generate PNMR (Politically Exposed Person / Non-Profit Organization Management Report) XML
 * For PEP and NPO relationship management and monitoring.
 */
export function generatePNMRXml(filing: GoAMLFilingData): string {
  const ref = filing.referenceNumber || `PNMR-${Date.now()}`;
  const lines: string[] = [
    generateXmlHeader('PNMR'),
    `<goAML xmlns="${GOAML_NAMESPACE}" version="${GOAML_VERSION}">`,
    `  <ReportHeader>`,
    `    <ReportCode>${REPORT_TYPE_CODES.PNMR}</ReportCode>`,
    `    <ReferenceNumber>${escapeXml(ref)}</ReferenceNumber>`,
    `    <FilingDate>${new Date().toISOString()}</FilingDate>`,
    `    <RegulatoryReference>FDL 10/2025</RegulatoryReference>`,
    `    <Jurisdiction>${escapeXml(filing.jurisdiction || 'AE')}</Jurisdiction>`,
    `    <SubmissionType>INITIAL</SubmissionType>`,
    `  </ReportHeader>`,
    generateReportingEntitySection(filing),
    generateSubjectSection(filing),
    generateTransactionSection(filing),
    generateNarrativeSection(filing),
    '  <PEPNPOManagement>',
    '    <Category>PEP</Category>',
    '    <RiskLevel>HIGH</RiskLevel>',
    '    <EnhancedDueDiligence>true</EnhancedDueDiligence>',
    '    <SeniorManagementApproval>true</SeniorManagementApproval>',
    '    <SourceOfWealthVerified>true</SourceOfWealthVerified>',
    '    <ReportingObligation>FDL 10/2025 Article 17; FATF Recommendation 12/13</ReportingObligation>',
    '  </PEPNPOManagement>',
    '</goAML>',
  ];
  return lines.join('\n');
}

// ─── Master XML Generation ──────────────────────────────────────────────────

/**
 * Generate goAML XML for any report type.
 * Automatically selects the correct template based on reportType.
 * Auto-detects CTR when amount >= AED 55,000.
 */
export function generateGoAMLXML(filing: GoAMLFilingData): string {
  const effectiveType = detectReportType(filing);

  switch (effectiveType) {
    case 'STR':
      return generateSTRXml({ ...filing, reportType: 'STR' });
    case 'SAR':
      return generateSARXml({ ...filing, reportType: 'SAR' });
    case 'CTR':
      return generateCTRXml({ ...filing, reportType: 'CTR' });
    case 'IFT':
      return generateIFTXml({ ...filing, reportType: 'IFT' });
    case 'PNMR':
      return generatePNMRXml({ ...filing, reportType: 'PNMR' });
    default:
      throw new Error(`Unsupported report type: ${effectiveType}`);
  }
}

// ─── XML Validation ─────────────────────────────────────────────────────────

/**
 * Validate the structure of a generated goAML XML document.
 * Performs structural checks (not full XSD validation).
 */
export function validateGoAMLXML(xml: string): XMLValidationResult {
  const errors: XMLValidationError[] = [];
  const warnings: string[] = [];

  // Check XML declaration
  if (!xml.startsWith('<?xml')) {
    errors.push({
      path: '/xml-declaration',
      message: 'Missing XML declaration',
      severity: 'error',
    });
  }

  // Check goAML root element
  if (!xml.includes('<goAML')) {
    errors.push({
      path: '/goAML',
      message: 'Missing goAML root element',
      severity: 'error',
    });
  }

  // Check namespace
  if (!xml.includes(GOAML_NAMESPACE) && !xml.includes('goaml')) {
    warnings.push('goAML namespace reference may be missing or incorrect');
  }

  // Check ReportHeader
  if (!xml.includes('<ReportHeader>')) {
    errors.push({
      path: '/goAML/ReportHeader',
      message: 'Missing ReportHeader section',
      severity: 'error',
    });
  } else {
    // Check required ReportHeader fields
    if (!xml.includes('<ReportCode>')) {
      errors.push({
        path: '/goAML/ReportHeader/ReportCode',
        message: 'Missing ReportCode in ReportHeader',
        severity: 'error',
      });
    }
    if (!xml.includes('<ReferenceNumber>')) {
      errors.push({
        path: '/goAML/ReportHeader/ReferenceNumber',
        message: 'Missing ReferenceNumber in ReportHeader',
        severity: 'error',
      });
    }
    if (!xml.includes('<FilingDate>')) {
      errors.push({
        path: '/goAML/ReportHeader/FilingDate',
        message: 'Missing FilingDate in ReportHeader',
        severity: 'error',
      });
    }
    if (!xml.includes('<Jurisdiction>')) {
      warnings.push('Jurisdiction field missing in ReportHeader (recommended for UAE filings)');
    }
  }

  // Check FDL 10/2025 reference
  if (!xml.includes('FDL 10/2025')) {
    warnings.push('FDL 10/2025 regulatory reference not found in XML header');
  }

  // Check ReportingEntity
  if (!xml.includes('<ReportingEntity>')) {
    errors.push({
      path: '/goAML/ReportingEntity',
      message: 'Missing ReportingEntity section',
      severity: 'error',
    });
  }

  // Check Subject
  if (!xml.includes('<Subject>')) {
    errors.push({
      path: '/goAML/Subject',
      message: 'Missing Subject section',
      severity: 'error',
    });
  }

  // Check Transaction (for CTR, STR, SAR, IFT)
  const reportCodeMatch = xml.match(/<ReportCode>(.*?)<\/ReportCode>/);
  const reportCode = reportCodeMatch?.[1] || '';
  if (['STR', 'SAR', 'CTR', 'IFT'].includes(reportCode) && !xml.includes('<Transaction>')) {
    errors.push({
      path: '/goAML/Transaction',
      message: 'Missing Transaction section for report type requiring transaction data',
      severity: 'error',
    });
  }

  // Check for amountAED (UAE-specific)
  if (xml.includes('<Transaction>') && !xml.includes('<AmountAED>')) {
    warnings.push('AmountAED field missing in Transaction (required for UAE CBUAE filings)');
  }

  // Check closing tag
  if (!xml.includes('</goAML>')) {
    errors.push({
      path: '/goAML',
      message: 'Missing goAML closing tag',
      severity: 'error',
    });
  }

  // Check for proper XML encoding
  if (!xml.includes('encoding="UTF-8"') && !xml.includes("encoding='UTF-8'")) {
    warnings.push('UTF-8 encoding declaration recommended for UAE FIU submissions');
  }

  // Check well-formedness: balanced tags
  const openTags = (xml.match(/<(\w+)[>\s]/g) || []).length;
  const closeTags = (xml.match(/<\/(\w+)>/g) || []).length;
  const selfClosingTags = (xml.match(/\/>/g) || []).length;
  if (Math.abs(openTags - closeTags - selfClosingTags) > 5) {
    warnings.push('XML tag balance appears off — potential malformation');
  }

  return {
    isValid: errors.filter((e) => e.severity === 'error').length === 0,
    errors,
    warnings,
  };
}

/**
 * Basic XSD structural validation.
 * Checks the XML against expected goAML v4.2 structure patterns.
 */
export function validateXSD(xml: string, xsdSchema?: string): XMLValidationResult {
  const result = validateGoAMLXML(xml);

  // If an XSD schema string is provided, perform additional structural checks
  if (xsdSchema) {
    // Check that the XML root element matches XSD target namespace
    const targetNsMatch = xsdSchema.match(/targetNamespace="([^"]+)"/);
    if (targetNsMatch) {
      const targetNs = targetNsMatch[1];
      if (!xml.includes(`xmlns="${targetNs}"`)) {
        result.errors.push({
          path: '/goAML',
          message: `XML namespace does not match XSD target namespace: ${targetNs}`,
          severity: 'error',
        });
      }
    }

    // Check version attribute from XSD
    const versionMatch = xsdSchema.match(/version="([^"]+)"/);
    if (versionMatch) {
      const xsdVersion = versionMatch[1];
      if (!xml.includes(`version="${xsdVersion}"`)) {
        result.warnings.push(`XML version attribute does not match XSD version: ${xsdVersion}`);
      }
    }

    // Check that required XSD elements are present in the XML
    const requiredElements = xsdSchema.match(/name="(\w+)"\s+type="[^"]*"\s+use="required"/g) || [];
    for (const elementMatch of requiredElements) {
      const nameMatch = elementMatch.match(/name="(\w+)"/);
      if (nameMatch) {
        const elemName = nameMatch[1];
        if (!xml.includes(`<${elemName}>`)) {
          result.errors.push({
            path: `/${elemName}`,
            message: `Required XSD element "${elemName}" not found in XML`,
            severity: 'error',
          });
        }
      }
    }
  }

  // Standard goAML v4.2 structural validation
  const structuralChecks = [
    { element: 'goAML', required: true },
    { element: 'ReportHeader', required: true },
    { element: 'ReportingEntity', required: true },
    { element: 'Subject', required: true },
    { element: 'Person', required: true },
    { element: 'FullName', required: true },
  ];

  for (const check of structuralChecks) {
    if (check.required && !xml.includes(`<${check.element}>`)) {
      result.errors.push({
        path: `/${check.element}`,
        message: `Required structural element "${check.element}" missing`,
        severity: 'error',
      });
    }
  }

  result.isValid = result.errors.filter((e) => e.severity === 'error').length === 0;
  return result;
}

/**
 * Get the CTR threshold in AED.
 */
export function getCTRThreshold(): number {
  return CTR_THRESHOLD_AED;
}

/**
 * Get the CBWT threshold in AED.
 */
export function getCBWTThreshold(): number {
  return CBWT_THRESHOLD_AED;
}
